### PR TITLE
ENH: Use target based includes

### PR DESCRIPTION
**Pull request by blowekamp**
Replace directly level includes, with target based includes. This allows for setting include properties on targets which allows for propagation to users of the libraries. Additionally, private and public scope can be applied.

### CODE REVIEW

**Comment by blowekamp** [comment]
@N-Dekker Please review.

File: Components/MovingImagePyramids/OpenCLMovingGenericPyramid/CMakeLists.txt [hunk 1]
```diff
@@ -5,9 +5,9 @@ if(ELASTIX_USE_OPENCL)
     elxOpenCLMovingGenericPyramid.hxx
     elxOpenCLMovingGenericPyramid.cxx)
 
-  include_directories(../MovingGenericPyramid)
-
   if(USE_OpenCLMovingdGenericPyramid)
```
Comment (N-Dekker) [inline Components/MovingImagePyramids/OpenCLMovingGenericPyramid/CMakeLists.txt]: There is a typo here! A letter `d` in the middle of `USE_OpenCLMovingdGenericPyramid`! Obviously not your fault, @blowekamp! It was introduced with 2ce0a0ae72845dc2cf08a5da6157fb1b56159472, more than 11 years ago. But as a consequence, the `target_include_directories` that you added is never executed here!

**Review by N-Dekker — CHANGES_REQUESTED** [review]
Very interesting, thanks @blowekamp 
It does not yet work when OpenCL support is enabled, so it still needs to be adjusted a little bit  🤷

File: Components/MovingImagePyramids/OpenCLMovingGenericPyramid/CMakeLists.txt (hunk 1 above)
Comment (N-Dekker) [reply Components/MovingImagePyramids/OpenCLMovingGenericPyramid/CMakeLists.txt]: @dpshamonin Hi Denis! Do you remember this code? I guess we should just remove the letter `d` from the middle of `USE_OpenCLMovingdGenericPyramid`, right?

**Comment by N-Dekker** [comment]
@blowekamp Can you please add the word CMake or CMakeLists to your commit subject line?

For example:

    ENH: Use target based includes in CMakeLists

File: Common/OpenCL/CMakeLists.txt [hunk 2]
```diff
@@ -61,6 +61,26 @@ target_link_libraries(elxOpenCL
   ${OPENCL_LIBRARIES}
 )
 
+target_include_directories(elxOpenCL PUBLIC ${OPENCL_INCLUDE_DIRS})
+target_compile_definitions(elxOpenCL PUBLIC ELASTIX_USE_OPENCL)
+
```
Comment (N-Dekker) [inline Common/OpenCL/CMakeLists.txt:66]: I'm getting compile errors saying:

    elastix\Common\OpenCL\ITKimprovements\itkOpenCLContext.cxx(19,10): error C1083: Cannot open include file: 'itkOpenCLKernels.h': No such file or directory

To fix these, maybe add the following line:

    target_include_directories(elxOpenCL PRIVATE ${OPENCL_KERNELS_DEBUG_PATH})

("itkOpenCLKernels.h.in" is configured to `${OPENCL_KERNELS_DEBUG_PATH}/itkOpenCLKernels.h`)

Comment (blowekamp) [reply Common/OpenCL/CMakeLists.txt:66]: I just tried and  FindOpenCL didn't find the headers on my linux or osx systems, and requires further investigations.

Comment (N-Dekker) [reply Common/OpenCL/CMakeLists.txt:66]: @blowekamp I have a few fixes that should be applied _before_ your PR:

 - Pull request #1427

Note that the `USE_OpenCLMovingdGenericPyramid` typo fix might have a git merge conflict with your proposed change in "Components/MovingImagePyramids/OpenCLMovingGenericPyramid/CMakeLists.txt", but it's really very simple: just remove the letter `d` from the middle!

Comment (N-Dekker) [reply Common/OpenCL/CMakeLists.txt:66]: @blowekamp Can you please rebase your PR onto the latest SuperElastix/elastix main branch? (Including the `USE_OpenCLMovingdGenericPyramid` typo fix.)

**Comment by N-Dekker** [comment]
> @blowekamp Can you please add the word CMake or CMakeLists to your commit subject line?

Thanks for your attempt to address my suggestion! I say "attempt", because it appeared in the wrong branch! [target_Based_includes](https://github.com/blowekamp/elastix/tree/target_Based_includes) is not the branch of this pull request! It is [target_based_includes](https://github.com/blowekamp/elastix/tree/target_based_includes) !!! Please check your [blowekamp/elastix/branches](https://github.com/blowekamp/elastix/branches)!

**Comment by blowekamp** [comment]
OK, things look correct now.

**Review by N-Dekker — APPROVED** [review]
Thank you very much, @blowekamp !
