### PR TITLE
COMP: Avoid GCC4 error xoutManager "use of deleted function", issue #331

### PR DESCRIPTION
**Pull request by N-Dekker**
Worked around a GCC 4.8.2 compile error on ITKElastix build, reported by Matt McCormick, issue #331 (xout on `develop` branch do not build on Linux / GCC 4.8):

> _deps/elx-src/Core/Kernel/elxElastixMain.cxx: In destructor ‘elastix::xoutManager::Guard::~Guard()’:
> _deps/elx-src/Core/Kernel/elxElastixMain.cxx:146:10: error: use of deleted function ‘{anonymous}::Data& {anonymous}::Data::operator=({anonymous}::Data&&)’
...
> /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’

### CODE REVIEW

**Comment by N-Dekker** [comment]
@thewtex Matt do you think this pull request would make GCC 4.8 happy?

**Comment by thewtex** [comment]
Thanks, Neils! Testing it out here: https://github.com/InsightSoftwareConsortium/ITKElastix/pull/78

**Comment by N-Dekker** [comment]
@thewtex Do I understand correctly from https://github.com/InsightSoftwareConsortium/ITKPythonPackage/pull/152#issuecomment-740684513 that this (rather tricky, rather ugly) workaround is no longer necessary, as GCC 4.8 no longer needs to be supported? 

We currently have GCC 7.5.0 on our SuperElastix/elastix CI (Ubuntu), which does not need this workaround.

**Comment by thewtex** [comment]
@N-Dekker yes :-)
