### ISSUE TITLE
Error in  C++ project while initializing Pointer object of type using itk::TransformixFilter<ImageType>; 

### ISSUE THREAD

**Issue by kyadav78** [SuperElastix/elastix#996]
I am using Elastix 5.1.0 and ITK5.3.0 verson in my C++ code , when using below code snippet i am getting errors:
C2259:'Xoutlibrary::xoutbase':cannot instantiate abstract class.

code:
#include "itkTransformixFilter.h"
#include "itkImage.h"
 constexpr unsigned int ImageDimension = 2;
using Pixeltype = float;
using ImageType = itk::Image<PixelType, ImageDimension>;

using TransformixFilterType = itk::TransformixFilter<ImageType>;
TransformixFilterType::Pointer transformixfilter = TransformixFilter::New();

i don't understand why i am getting error from  xoutlibrary .
had anyone face such issue?

Regards
Kunal

**Comment by N-Dekker** [comment]
Thank you for your question, @kyadav78 It looks like a compiler problem to me! Can you tell us exactly which compiler version you are using?

Anyway, I think you can work around the problem by reverting the following commit: aa32e1f49dc0e50ab77435b4adccb72d38e0280b (which was introduced by pull request #397)

More specifically, the destructor should be as it was before that commit:

    virtual ~xoutbase() = default;

By the way, we are no longer using xoutbase with the current revision, from the main branch of the elastix git repository. So this would just be a quick-fix for your local code. But it could also be solved by upgrading your compiler, maybe.

**Comment by kyadav78** [comment]
Hi Niels,
    Thanks for the prompt respond, i am able to resolve that issue.
But now i am getting linking error  and attaching you the screen shot. i am on critical project and time line is really tight, can you please suggest how to resolve the linking error?

**Comment by kyadav78** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: int __thiscall elastix::TransformixMain::Run(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::vector<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > >,class std::allocator<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > > > > const &,class itk::TransformBaseTemplate<double> *)" (?Run@TransformixMain@elastix@@QAEHABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@ABV?$vector@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@std@@V?$allocator@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@std@@@2@@4@PAV?$TransformBaseTemplate@N@itk@@@Z) referenced in function "protected: virtual void __thiscall itk::TransformixFilter<class itk::Image<float,2> >::GenerateData(void)" (?GenerateData@?$TransformixFilter@V?$Image@M$01@itk@@@itk@@MAEXXZ)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK1120	7 unresolved externals	transformix	C:\Users\e182000\source\repos\transformix\Debug\transformix.exe	1	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	transformix	F:\elast\ITK-5.3.0\buildx86\Modules\ThirdParty\KWSys\src\itksys\Configure.hxx	37	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	transformix	F:\elast\ITK-5.3.0\buildx86\Modules\ThirdParty\KWSys\src\itksys\Configure.hxx	40	
Error	LNK2001	unresolved external symbol "protected: virtual int __thiscall elastix::TransformixMain::InitDBIndex(void)" (?InitDBIndex@TransformixMain@elastix@@MAEHXZ)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2019	unresolved external symbol "protected: virtual __thiscall elastix::TransformixMain::~TransformixMain(void)" (??1TransformixMain@elastix@@MAE@XZ) referenced in function "protected: virtual void * __thiscall elastix::TransformixMain::`scalar deleting destructor'(unsigned int)" (??_GTransformixMain@elastix@@MAEPAXI@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual int __thiscall elastix::TransformixMain::Run(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &)" (?Run@TransformixMain@elastix@@UAEHABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual int __thiscall elastix::TransformixMain::Run(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > > const &)" (?Run@TransformixMain@elastix@@UAEHABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@ABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@4@@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual int __thiscall elastix::TransformixMain::Run(void)" (?Run@TransformixMain@elastix@@UAEHXZ)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall elastix::TransformixMain::SetInputImageContainer(class itk::VectorContainer<unsigned int,class itk::SmartPointer<class itk::DataObject> > *)" (?SetInputImageContainer@TransformixMain@elastix@@UAEXPAV?$VectorContainer@IV?$SmartPointer@VDataObject@itk@@@itk@@@itk@@@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1

**Comment by kyadav78** [comment]
Thanks Niels , i am able to resolve the initial issue with you suggestion but i have started getting linking error as you can see in my last comment. i am on critical project with very tight time line. please help me in resolving the new linking issue.

**Comment by kyadav78** [comment]
i am using visual studio 2017  x86 native compiler.

**Comment by kyadav78** [comment]
sorry i could not copy complete linking error so reposting:




Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "protected: virtual int __thiscall elastix::TransformixMain::InitDBIndex(void)" (?InitDBIndex@TransformixMain@elastix@@MAEHXZ)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK1120	7 unresolved externals	transformix	C:\Users\e182000\source\repos\transformix\Debug\transformix.exe	1	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	transformix	F:\elast\ITK-5.3.0\buildx86\Modules\ThirdParty\KWSys\src\itksys\Configure.hxx	37	
Error (active)	E2512	the argument to a feature-test macro must be a simple identifier	transformix	F:\elast\ITK-5.3.0\buildx86\Modules\ThirdParty\KWSys\src\itksys\Configure.hxx	40	
Error	LNK2019	unresolved external symbol "protected: virtual __thiscall elastix::TransformixMain::~TransformixMain(void)" (??1TransformixMain@elastix@@MAE@XZ) referenced in function "protected: virtual void * __thiscall elastix::TransformixMain::`scalar deleting destructor'(unsigned int)" (??_GTransformixMain@elastix@@MAEPAXI@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2019	unresolved external symbol "public: int __thiscall elastix::TransformixMain::Run(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::vector<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > >,class std::allocator<class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > > > > const &,class itk::TransformBaseTemplate<double> *)" (?Run@TransformixMain@elastix@@QAEHABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@ABV?$vector@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@std@@V?$allocator@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@std@@@2@@4@PAV?$TransformBaseTemplate@N@itk@@@Z) referenced in function "protected: virtual void __thiscall itk::TransformixFilter<class itk::Image<float,2> >::GenerateData(void)" (?GenerateData@?$TransformixFilter@V?$Image@M$01@itk@@@itk@@MAEXXZ)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual int __thiscall elastix::TransformixMain::Run(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &)" (?Run@TransformixMain@elastix@@UAEHABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual int __thiscall elastix::TransformixMain::Run(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > > const &)" (?Run@TransformixMain@elastix@@UAEHABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@std@@ABV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@2@@std@@@2@@4@@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual int __thiscall elastix::TransformixMain::Run(void)" (?Run@TransformixMain@elastix@@UAEHXZ)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1	
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall elastix::TransformixMain::SetInputImageContainer(class itk::VectorContainer<unsigned int,class itk::SmartPointer<class itk::DataObject> > *)" (?SetInputImageContainer@TransformixMain@elastix@@UAEXPAV?$VectorContainer@IV?$SmartPointer@VDataObject@itk@@@itk@@@itk@@@Z)	transformix	C:\Users\e182000\source\repos\transformix\transformix\transformix.obj	1

**Comment by N-Dekker** [comment]
@kyadav78  In order to use `itk::TransformixFilter`, you must make sure that your project links to the transformix library. The lib file is probably named something like "transformix-5.1.lib" Do you use CMake for your own project? If so, then you may use a CMake command like

    target_link_libraries(kyadav78_project PRIVATE ${ITK_LIBRARIES} transformix_lib)

A similar example (but then for Elastix) is at https://github.com/SuperElastix/elastix/blob/c3fb0eba5644a2122e11bd25f5042e47d3b4ec71/dox/externalproject/CMakeLists.txt


Hope that helps, Niels

**Comment by kyadav78** [comment]
Hi N-Dekker,
 Thank you very much for your response. i am successfully run and compiled my project, i have linked the list of library mainly "transformix-5.1.lib" in vs linker.
We can close this ticket.
i cannot upgrade my project to x64  now.  it may take one or two years. i will be using 32-bit compiled version of elastix,ITK and Opencv. i will reach out to you if i face any issue.

Thanks
Kunal
