### ISSUE TITLE
xout on `develop` branch do not build on Linux / GCC 4.8

### ISSUE THREAD

**Issue by thewtex** [SuperElastix/elastix#331]
As discussed in:

https://github.com/InsightSoftwareConsortium/ITKElastix/pull/78

and reported in:

https://github.com/InsightSoftwareConsortium/ITKElastix/runs/1282030109?check_suite_focus=true

recent changes on the `develop` branch are not building on Linux / GCC 4.8, which is required for Python packages.

**Comment by N-Dekker** [comment]
Hi Matt,

Was this issue not fixed by pull request #330 ?

Commit https://github.com/SuperElastix/elastix/commit/9b4d0a11164daff6b4b44fb8a8f0d5d927457576

Please also check my question at https://github.com/SuperElastix/elastix/pull/330#issuecomment-712938116

**Comment by thewtex** [comment]
Hi Neils,

It looks like #330 helped, but there are more build errors:

```
_deps/elx-src/Core/Kernel/elxElastixMain.cxx: In destructor ‘elastix::xoutManager::Guard::~Guard()’:
_deps/elx-src/Core/Kernel/elxElastixMain.cxx:146:10: error: use of deleted function ‘{anonymous}::Data& {anonymous}::Data::operator=({anonymous}::Data&&)’
   g_data = {};
          ^
_deps/elx-src/Core/Kernel/elxElastixMain.cxx:49:8: note: ‘{anonymous}::Data& {anonymous}::Data::operator=({anonymous}::Data&&)’ is implicitly deleted because the default definition would be ill-formed:
 struct Data
        ^
_deps/elx-src/Core/Kernel/elxElastixMain.cxx:49:8: error: use of deleted function ‘std::basic_ofstream<char>& std::basic_ofstream<char>::operator=(const std::basic_ofstream<char>&)’
In file included from ../../../ITK-source/ITK/Modules/IO/ImageBase/include/itkImageIOBase.h:38:0,
                 from ../../../ITK-source/ITK/Modules/IO/ImageBase/include/itkImageFileReader.h:24,
                 from _deps/elx-src/Core/Kernel/elxElastixBase.h:40,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:24,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:599:11: note: ‘std::basic_ofstream<char>& std::basic_ofstream<char>::operator=(const std::basic_ofstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/istream:39:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/sstream:38,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:53,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkLightObject.h:21,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from _deps/elx-src/Core/Install/elxComponentDatabase.h:22,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:21,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:58:11: note: ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/istream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/sstream:38,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:53,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkLightObject.h:21,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from _deps/elx-src/Core/Install/elxComponentDatabase.h:22,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:21,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:42:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/istream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/sstream:38,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:53,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkLightObject.h:21,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from _deps/elx-src/Core/Install/elxComponentDatabase.h:22,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:21,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/ios_base.h:789:5: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private
     operator=(const ios_base&);
     ^
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:44:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/istream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/sstream:38,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:53,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkLightObject.h:21,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from _deps/elx-src/Core/Install/elxComponentDatabase.h:22,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:21,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from ../../../ITK-source/ITK/Modules/IO/ImageBase/include/itkImageIOBase.h:38:0,
                 from ../../../ITK-source/ITK/Modules/IO/ImageBase/include/itkImageFileReader.h:24,
                 from _deps/elx-src/Core/Kernel/elxElastixBase.h:40,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:24,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’
     class basic_ofstream : public basic_ostream<_CharT,_Traits>
           ^
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:72:11: note: ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/ios:43:0,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/istream:38,
                 from /opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/sstream:38,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkMacro.h:53,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkLightObject.h:21,
                 from ../../../ITK-source/ITK/Modules/Core/Common/include/itkObject.h:31,
                 from _deps/elx-src/Core/Install/elxComponentDatabase.h:22,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:21,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/streambuf:810:7: error: ‘std::basic_streambuf<_CharT, _Traits>& std::basic_streambuf<_CharT, _Traits>::operator=(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       operator=(const basic_streambuf&) { return *this; };
       ^
In file included from ../../../ITK-source/ITK/Modules/IO/ImageBase/include/itkImageIOBase.h:38:0,
                 from ../../../ITK-source/ITK/Modules/IO/ImageBase/include/itkImageFileReader.h:24,
                 from _deps/elx-src/Core/Kernel/elxElastixBase.h:40,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.h:24,
                 from _deps/elx-src/Core/Kernel/elxElastixMain.cxx:27:
/opt/rh/devtoolset-2/root/usr/include/c++/4.8.2/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
```

Here: https://github.com/InsightSoftwareConsortium/ITKElastix/pull/78/checks?check_run_id=1287715419

**Comment by N-Dekker** [comment]
Thanks for reporting this compiler error, Matt. It appears triggered by pull request #303, which fixed the bug that output streams did not get closed properly.  

It is really another limitation of GCC 4.x Apparently it does not support C++11 move-assignment for I/O streams. As I tried by doing `myStream = std::ofstream{}` at https://godbolt.org/z/MP7ejG

Would it be possible for you to upgrade to GCC 5.x? elastix is currently tested on ubuntu-16.04, having GNU 5.5.0. As I said, I would prefer to move forward to C++14, but at least going from GCC 4 to GCC 5 is a step forward.

**Comment by thewtex** [comment]
We can upgrade to GCC 8, which supports C++14, by building with the [manylinux2014](https://www.python.org/dev/peps/pep-0599/) toolchain, but that will come with ITK 5.2, and we currently need to build against ITK 5.1 to create distributable Python packages.

**Comment by N-Dekker** [comment]
Thanks for your reply. So you cannot currently use GCC >= 5  to create distributable Python packages?

**Comment by thewtex** [comment]
The current ITK 5.1 distributable Python packages are created with GCC 4.8 via the manylinux1 toolchain. Since we build ITKElastix against it, we also have to use GCC 4.8.

**Comment by thewtex** [comment]
Green again :green_heart: -- thank you @N-Dekker !
